"""
SQL Models

Pydantic models representing the Text2SQL pipeline.

These models provide a strongly typed contract between the
SQL Generator, SQL Validator, SQL Executor, and Hybrid
services.

The BusinessResponse model references these models instead of
using raw dictionaries.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field


# ==========================================================
# SQL Generation
# ==========================================================


class SQLGeneration(BaseModel):
    """
    Represents the SQL generated by the LLM.
    """

    model_config = ConfigDict(extra="forbid")

    sql: str = Field(
        ...,
        description="Generated SQL query.",
        min_length=1,
    )


# ==========================================================
# SQL Validation
# ==========================================================


class SQLValidationResult(BaseModel):
    """
    Result of SQL safety validation.
    """

    model_config = ConfigDict(extra="forbid")

    valid: bool = Field(
        ...,
        description="Whether the SQL passed validation.",
    )

    reason: str | None = Field(
        default=None,
        description="Reason for validation failure.",
    )


# ==========================================================
# SQL Execution
# ==========================================================


class SQLExecutionResult(BaseModel):
    """
    Result returned after executing a validated SQL query.
    """

    model_config = ConfigDict(extra="forbid")

    columns: list[str] = Field(
        default_factory=list,
        description="Column names returned by the query.",
    )

    rows: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Query result rows.",
    )

    row_count: int = Field(
        default=0,
        ge=0,
        description="Number of rows returned.",
    )


# ==========================================================
# SQL Refusal
# ==========================================================


class SQLRefusal(BaseModel):
    """
    Returned when SQL generation is intentionally refused.
    """

    model_config = ConfigDict(extra="forbid")

    refuse: bool = Field(
        default=True,
        frozen=True,
    )

    reason: str = Field(
        ...,
        description="Reason SQL generation was refused.",
    )